// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRdF3KD9YP5ErdfX1SIt0vxUb9DK3BCg',
    appId: '1:397331530707:web:506c795478a9e78d306526',
    messagingSenderId: '397331530707',
    projectId: 'apimusic-528b7',
    authDomain: 'apimusic-528b7.firebaseapp.com',
    storageBucket: 'apimusic-528b7.firebasestorage.app',
    measurementId: 'G-PX5VL51PNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7raAezcN4m3kKunVCbBHYGzY1zy-WX0M',
    appId: '1:397331530707:android:9af53cf6113313f1306526',
    messagingSenderId: '397331530707',
    projectId: 'apimusic-528b7',
    storageBucket: 'apimusic-528b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMH3bplhgB2rTrb0esqHJTziZXbLn5DW0',
    appId: '1:397331530707:ios:5f995e866fda44f6306526',
    messagingSenderId: '397331530707',
    projectId: 'apimusic-528b7',
    storageBucket: 'apimusic-528b7.firebasestorage.app',
    iosBundleId: 'com.example.cineFavorite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMH3bplhgB2rTrb0esqHJTziZXbLn5DW0',
    appId: '1:397331530707:ios:5f995e866fda44f6306526',
    messagingSenderId: '397331530707',
    projectId: 'apimusic-528b7',
    storageBucket: 'apimusic-528b7.firebasestorage.app',
    iosBundleId: 'com.example.cineFavorite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsRdF3KD9YP5ErdfX1SIt0vxUb9DK3BCg',
    appId: '1:397331530707:web:b11f7a47e40e8226306526',
    messagingSenderId: '397331530707',
    projectId: 'apimusic-528b7',
    authDomain: 'apimusic-528b7.firebaseapp.com',
    storageBucket: 'apimusic-528b7.firebasestorage.app',
    measurementId: 'G-GSCHZXWE7B',
  );

}