// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzu335Hh_SnufalivEtz4XY8wAGakZkgk',
    appId: '1:191096450435:web:33ccd99e12370956875ab6',
    messagingSenderId: '191096450435',
    projectId: 'cinefavorite-turma-app',
    authDomain: 'cinefavorite-turma-app.firebaseapp.com',
    storageBucket: 'cinefavorite-turma-app.firebasestorage.app',
    measurementId: 'G-8BR9ZTPPVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0hiTCGJCkrCspeh_-MYepBLvZ7sRwkxg',
    appId: '1:191096450435:android:bb1b6f12d4ef5721875ab6',
    messagingSenderId: '191096450435',
    projectId: 'cinefavorite-turma-app',
    storageBucket: 'cinefavorite-turma-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU3cFmJPDuAJ78s2qrpKqjEqFsdRGO-iM',
    appId: '1:191096450435:ios:f833d40868f9dfce875ab6',
    messagingSenderId: '191096450435',
    projectId: 'cinefavorite-turma-app',
    storageBucket: 'cinefavorite-turma-app.firebasestorage.app',
    iosBundleId: 'com.example.cineFavorite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU3cFmJPDuAJ78s2qrpKqjEqFsdRGO-iM',
    appId: '1:191096450435:ios:f833d40868f9dfce875ab6',
    messagingSenderId: '191096450435',
    projectId: 'cinefavorite-turma-app',
    storageBucket: 'cinefavorite-turma-app.firebasestorage.app',
    iosBundleId: 'com.example.cineFavorite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzu335Hh_SnufalivEtz4XY8wAGakZkgk',
    appId: '1:191096450435:web:c04028c436811319875ab6',
    messagingSenderId: '191096450435',
    projectId: 'cinefavorite-turma-app',
    authDomain: 'cinefavorite-turma-app.firebaseapp.com',
    storageBucket: 'cinefavorite-turma-app.firebasestorage.app',
    measurementId: 'G-VZ7EYPTC28',
  );
}
